const BACKEND_URL = `http://localhost:3000`;
const NOTIFICATION_SERVICE_URL = `http://localhost:3003`;
const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  SERVER_ERROR: 500,
};

export { BACKEND_URL, NOTIFICATION_SERVICE_URL, HTTP_STATUS };
